"""Initial migration.

Revision ID: b34c8858ec8b
Revises: 
Create Date: 2021-05-25 18:09:38.971725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b34c8858ec8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Departments',
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('department_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_index(op.f('ix_Departments_department_id'), 'Departments', ['department_id'], unique=False)
    op.create_index(op.f('ix_Departments_department_name'), 'Departments', ['department_name'], unique=False)
    op.create_table('Employee',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('employee_name', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['Departments.department_id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_index(op.f('ix_Employee_employee_id'), 'Employee', ['employee_id'], unique=False)
    op.create_index(op.f('ix_Employee_employee_name'), 'Employee', ['employee_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Employee_employee_name'), table_name='Employee')
    op.drop_index(op.f('ix_Employee_employee_id'), table_name='Employee')
    op.drop_table('Employee')
    op.drop_index(op.f('ix_Departments_department_name'), table_name='Departments')
    op.drop_index(op.f('ix_Departments_department_id'), table_name='Departments')
    op.drop_table('Departments')
    # ### end Alembic commands ###
